import Head from 'next/head'
import { Weather } from '@/components/Weather'
import { ChakraProvider } from '@chakra-ui/react'
import { Layout } from '@/components/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Task Admin</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <ChakraProvider>
        <Layout>
          <Weather />
        </Layout>
      </ChakraProvider>
    </>
  )
}
